database:
  project_id: "gen-aac-2025"
  aac_image_bucket_name: "genaac-image-log"
  aac_log_database_id: "genaac-api-log"
  
model:
  primary_llm: "claude-sonnet-4-5-20250929"
  secondary_llm: "gemini/gemini-2.5-pro"
  imagen: "imagen-4.0-generate-001"

