database:
  project_id: "gen-aac-2025"
  aac_image_bucket_name: "genaac-image-log"
  aac_log_database_id: "genaac-api-log"
  
model:
  primary_banana: "openrouter/google/gemini-3-pro-image-preview"
  secondary_banana: "gemini/gemini-3-pro-image-preview"
  imagen: "imagen-4.0-generate-001"

